services:
  postgres:
    container_name: innova-db
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - innova-network

volumes:
  postgres-data:
networks:
  innova-network:
    driver: bridge
